<a href="https://colab.research.google.com/github/rghdzarad/31109170100123_Library/blob/main/31109170100123_Library_project_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **- The Name 👤: `Raghad Mohamed Abd El-Alim Malek Zarad`**
# **- The Student ID 🪪 : `EYOUTH-31109170100123`**
# **- The Project Name 📝 : `City Library After-School Program`**

**- The Project Description :**

* A city library runs an `After-School Program` for students. The program keeps track of two things: which students are members, and which books each member has borrowed.

* Every summer, the library also hosts an event called the `Reading Kickoff`. At this event, a student can borrow a book without using their membership card. Because there's no card involved, these borrowing records aren't stored with the rest — they're logged separately, on the library's website.

*  The program coordinator is now writing an `End-of-Summer Reading Report`, and needs the data to be accurate and complete before that report can be written.

**- 🎒 My Role in the Project :**

`I am the library's data assistant. I'm the one responsible for handing over the data in a shape someone else can actually work with.`

Now we will start solving the tasks.

- We have 3 tasks to do in the project :
* Task 1 : Data Gathering & combination `(Combined Data)`
* Task 2 : Data Integrity `(Cleaned Data)`
* Task 3 : Data Fairness & Version Control

# **Checking the Cloud Machine**

In [1452]:
import sys , platform
print(f"Python Version : {sys.version}")
print(f"Cloud Machine : {platform.node()}")

Python Version : 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
Cloud Machine : 92b3f5b7d146

# **Importing all the required libraries in python**

In [1453]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3 as sql
from bs4 import BeautifulSoup
import requests
import json

# importing the warnings library to prevent any errors from the library
import warnings
warnings.filterwarnings("ignore")

### we will import the 3 sources of data to work on (db , json , html) to explore them  , answer the questions , and merge the 3 sources into 1 CSV File .

# **Task 1**

### The SQL database

In [1454]:
# the database connection
conn = sql.connect("/content/level3_final_project_library.db")

# function to ease working with SQL queries
def run(query):
    return pd.read_sql_query(query, conn)

# getting the tables from the database
members = run("SELECT * FROM members")
books = run("SELECT * FROM books")
checkouts = run("SELECT * FROM checkouts")

Exploring the Members Table

In [1455]:
print(f"The Table :\n {members}")
print()
print(f"The Dataset Shape : {members.shape}")
print()
print(f"The Dataset Info :\n {members.info()}")
print()
print(f"The statistical Description :\n {members.describe(include=np.number)}")
print()
print(f"The columns in the table : \n {members.columns.to_list()}")

The Table :
     member_id first_name last_name  grade neighborhood membership_status  \
0        1001      Salma   Ibrahim    8.0        Maadi            Active
1        1002      Fares     Saleh    9.0        Maadi            Active
2        1003     Bassel    Hegazy    6.0        Maadi            Active
3        1004      Fares     Wahba    7.0        Maadi          inactive
4        1005    Youssef     Halim    9.0        Maadi            Active
..        ...        ...       ...    ...          ...               ...
75       1076       Dina     Wahba    7.0       Shubra            Active
76       1077       Lina    Rashad    6.0       Shubra            Active
77       1078     Habiba     Osman    7.0       Shubra          INACTIVE
78       1079       Rana     Osman    8.0       Shubra            Active
79       1080     Bassel     Wahba    9.0       Shubra            Active

     join_date
0   2023-04-05
1         None
2   2025-04-23
3   2024-10-09
4   2024-05-05
..         ...
75  2025-12-13
76  2023-07-08
77  2023-08-05
78  2024-10-27
79  2023-12-28

[80 rows x 7 columns]

The Dataset Shape : (80, 7)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   member_id          80 non-null     int64
 1   first_name         80 non-null     object
 2   last_name          80 non-null     object
 3   grade              74 non-null     float64
 4   neighborhood       80 non-null     object
 5   membership_status  80 non-null     object
 6   join_date          76 non-null     object
dtypes: float64(1), int64(1), object(5)
memory usage: 4.5+ KB
The Dataset Info :
 None

The statistical Description :
        member_id      grade
count    80.0000  74.000000
mean   1040.5000   7.364865
std      23.2379   1.117413
min    1001.0000   6.000000
25%    1020.7500   6.000000
50%    1040.5000   7.000000
75%    1060.2500   8.000000
max    1080.0000   9.000000

The columns in the table :
 ['member_id', 'first_name', 'last_name', 'grade', 'neighborhood', 'membership_status', 'join_date']

Exploring the Books Table

In [1456]:
print(f"The Table :\n {books}")
print()
print(f"The Dataset Shape : {books.shape}")
print()
print(f"The Dataset Info :\n {books.info()}")
print()
print(f"The statistical Description :\n {books.describe(include=np.number)}")
print()
print(f"The columns in the table : \n {books.columns.to_list()}")

The Table :
     book_id                    title          author
0       501          The Silver Kite   Amina Darwish
1       502           Desert Compass   Amina Darwish
2       503        The Lantern Maker    Adel Roushdy
3       504      Rooftop Astronomers    Adel Roushdy
4       505      Letters to the Nile       Aya Hafez
5       506      The Paper Boat Club       Aya Hafez
6       507    Fossils and Fireflies     Dalia Serry
7       508    The Quiet Observatory     Dalia Serry
8       509      Marbles and Mirrors     Diaa Sultan
9       510    The Missing Metronome     Diaa Sultan
10      511     Winter in Alexandria    Farida Anwar
11      512   The Cartographer's Cat    Farida Anwar
12      513   Circuits for Beginners    Galal Mounir
13      514    The Robot in Row Nine    Galal Mounir
14      515       Songs of the Oasis      Hoda Bakry
15      516  The Beekeeper's Almanac      Hoda Bakry
16      517  Shadows on the Corniche     Hani Nagati
17      518     The Ninth Lighthouse     Hani Nagati
18      519         Kites Over Cairo  Jasmine Wahdan
19      520     The Copper Telescope  Jasmine Wahdan
20      521    A Garden of Equations      Karim Elwy
21      522      The Puzzle Merchant      Karim Elwy
22      523    Footsteps in the Dust    Laila Shokry
23      524    The Weaver's Daughter    Laila Shokry
24      525     Storms and Sailboats   Mahmoud Rafei
25      526    The Clockwork Orchard   Mahmoud Rafei
26      527     Notes from the Delta  Mona Kholoussy
27      528        The Glass Beehive  Mona Kholoussy
28      529   Riddles of the Red Sea    Sara Tantawy
29      530        The Sandstone Key    Sara Tantawy
30      531    Voices in the Library     Samir Zohdy
31      532        The Last Bookmark     Samir Zohdy

The Dataset Shape : (32, 3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   book_id  32 non-null     int64
 1   title    32 non-null     object
 2   author   32 non-null     object
dtypes: int64(1), object(2)
memory usage: 900.0+ bytes
The Dataset Info :
 None

The statistical Description :
           book_id
count   32.000000
mean   516.500000
std      9.380832
min    501.000000
25%    508.750000
50%    516.500000
75%    524.250000
max    532.000000

The columns in the table :
 ['book_id', 'title', 'author']

Exploring the Checkouts Table

In [1457]:
print(f"The Table :\n {checkouts}")
print()
print(f"The Dataset Shape : {checkouts.shape}")
print()
print(f"The Dataset Info :\n {checkouts.info()}")
print()
print(f"The statistical Description :\n {checkouts.describe(include=np.number)}")
print()
print(f"The columns in the table : \n {checkouts.columns.to_list()}")

The Table :
      checkout_id  member_id  book_id checkout_date return_date
0           9263       1047      517    2024-10-21  2024-11-07
1           9340       1072      513    2025-08-24  2025-09-01
2           9231       1053      523    2024-02-04  2024-02-16
3           9129       1032      513    2025-06-21  2025-06-29
4           9370       1079      511    2025-11-11  2025-12-03
..           ...        ...      ...           ...         ...
386         9232       1044      513    2025-05-26  2025-06-11
387         9084       1008      511    2024-06-27  2024-07-22
388         9116       1024      519    2025-01-10  2025-02-09
389         9352       1076      501    2025-02-02        None
390         9246       1044      529    2025-06-25  2025-07-04

[391 rows x 5 columns]

The Dataset Shape : (391, 5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 391 entries, 0 to 390
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   checkout_id    391 non-null    int64
 1   member_id      391 non-null    int64
 2   book_id        391 non-null    int64
 3   checkout_date  391 non-null    object
 4   return_date    326 non-null    object
dtypes: int64(3), object(2)
memory usage: 15.4+ KB
The Dataset Info :
 None

The statistical Description :
        checkout_id    member_id     book_id
count   391.000000   391.000000  391.000000
mean   9192.611253  1039.841432  513.271100
std     110.279771    22.925977    8.982785
min    9001.000000  1001.000000  501.000000
25%    9097.500000  1020.000000  507.000000
50%    9193.000000  1034.000000  513.000000
75%    9287.500000  1060.500000  519.000000
max    9383.000000  1080.000000  532.000000

The columns in the table :
 ['checkout_id', 'member_id', 'book_id', 'checkout_date', 'return_date']

### The json file

In [1458]:
json_df = pd.read_json("/content/level3_final_project_book_catalog.json")
print(f"The Table :\n {json_df}")
print()
print(f"The Dataset Shape : {json_df.shape}")
print()
print(f"The Dataset Info :\n {json_df.info()}")
print()
print(f"The statistical Description :\n {json_df.describe(include=np.number)}")
print()
print(f"The columns in the table : \n {json_df.columns.to_list()}")

The Table :
     book_id            genre  pages  publication_year            publisher
0       501        Adventure    128            2017.0           Nile Press
1       502        Adventure    109            2018.0          Delta House
2       503       Historical    259               NaN           Nile Press
3       504          Science    319            2009.0  Cairo Young Readers
4       505       Historical    216            2024.0          Oasis Books
5       506       Friendship    183               NaN           Nile Press
6       507          Science    160            2024.0           Nile Press
7       508          Science    306            2011.0          Oasis Books
8       509          Mystery    221            2011.0           Nile Press
9       510          Mystery    134            2013.0  Cairo Young Readers
10      511       Historical    117            2016.0           Nile Press
11      512        Adventure    238            2022.0          Delta House
12      513          Science    294            2021.0          Oasis Books
13      514  Science Fiction    328            2023.0  Cairo Young Readers
14      515           Poetry    316            2022.0  Cairo Young Readers
15      516           Nature    241            2010.0           Nile Press
16      517          Mystery    338            2015.0          Delta House
17      518        Adventure    163            2011.0          Delta House
18      519       Friendship    157            2014.0           Nile Press
19      520  Science Fiction    136            2009.0          Oasis Books
20      521          Science    211            2024.0  Cairo Young Readers
21      522          Mystery    104            2016.0  Cairo Young Readers
22      523       Historical    276            2018.0          Oasis Books
23      524       Historical    114            2016.0  Cairo Young Readers
24      525        Adventure    297            2015.0          Oasis Books
25      526  Science Fiction    125            2016.0          Delta House
26      527           Nature    328            2017.0          Delta House
27      528           Nature    114            2010.0          Delta House
28      529          Mystery    298               NaN  Cairo Young Readers
29      530        Adventure    208            2012.0          Oasis Books
30      531       Friendship    272            2018.0          Oasis Books
31      532       Friendship    337            2017.0          Oasis Books

The Dataset Shape : (32, 5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   book_id           32 non-null     int64
 1   genre             32 non-null     object
 2   pages             32 non-null     int64
 3   publication_year  29 non-null     float64
 4   publisher         32 non-null     object
dtypes: float64(1), int64(2), object(2)
memory usage: 1.4+ KB
The Dataset Info :
 None

The statistical Description :
           book_id       pages  publication_year
count   32.000000   32.000000         29.000000
mean   516.500000  220.218750       2016.172414
std      9.380832   81.556525          4.736401
min    501.000000  104.000000       2009.000000
25%    508.750000  135.500000       2012.000000
50%    516.500000  218.500000       2016.000000
75%    524.250000  297.250000       2018.000000
max    532.000000  338.000000       2024.000000

The columns in the table :
 ['book_id', 'genre', 'pages', 'publication_year', 'publisher']

### The html file (website)

In [1459]:
html_tables = pd.read_html("/content/level3_final_project_event_signups.html")
the_table = html_tables[0]
print(f"The Table :\n {the_table}")
print()
print(f"The Dataset Shape : {the_table.shape}")
print()
print(f"The Dataset Info :\n {the_table.info()}")
print()
print(f"The statistical Description :\n {the_table.describe(include=np.number)}")
print()
print(f"The columns in the table : \n {the_table.columns.to_list()}")

The Table :
     Member ID  Book ID Checkout Date
0        1026      522    2025-07-11
1        1049      520    2025-07-11
2        1062      525    2025-07-05
3        1065      520    2025-07-07
4        1104      515    2025-07-07
5        1009      503    2025-07-09
6        1063      522    2025-07-07
7        1022      511    2025-07-12
8        1029      523    2025-07-09
9        1201      509    2025-07-10
10       1005      513    2025-07-10
11       1104      526    2025-07-05
12       1058      518    2025-07-08
13       1002      521    2025-07-08
14       1150      530    2025-07-10
15       1041      504    2025-07-05
16       1055      526    2025-07-11
17       1061      513    2025-07-06
18       1012      509    2025-07-11
19       1007      510    2025-07-07
20       1073      530    2025-07-07
21       1003      501    2025-07-08
22       1017      507    2025-07-11
23       1061      504    2025-07-06
24       1201      523    2025-07-08
25       1041      512    2025-07-06

The Dataset Shape : (26, 3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Member ID      26 non-null     int64
 1   Book ID        26 non-null     int64
 2   Checkout Date  26 non-null     object
dtypes: int64(2), object(1)
memory usage: 756.0+ bytes
The Dataset Info :
 None

The statistical Description :
          Member ID     Book ID
count    26.000000   26.000000
mean   1058.500000  516.038462
std      54.961259    8.627773
min    1002.000000  501.000000
25%    1018.250000  509.250000
50%    1052.000000  516.500000
75%    1064.500000  522.750000
max    1201.000000  530.000000

The columns in the table :
 ['Member ID', 'Book ID', 'Checkout Date']

Now , We will make a copy of the original datasets to return to them if needed

In [1460]:
# the database copy
members_copy = members.copy()
books_copy = books.copy()
checkouts_copy = checkouts.copy()

# the json copy
json_df_copy = json_df.copy()

# the html copy
the_table_copy = the_table.copy()

## **Answering the 5 Question :**

Question 1 : How much is each member borrowing ?

In [1461]:
# Question 1: How much is each member borrowing?

Q1 = """SELECT members.member_id,
                  members.first_name,
                  members.last_name,
                  COUNT(checkouts.checkout_id) AS the_number_of_borrowings
FROM checkouts
JOIN members ON checkouts.member_id = members.member_id
GROUP BY members.first_name, members.last_name
"""

run(Q1)

    member_id first_name last_name  the_number_of_borrowings
0        1017       Adam      Badr                         2
1        1065       Adam     Fahmy                        17
2        1053       Adam    Shafik                         5
3        1057      Ahmed     Fahmy                        10
4        1049      Ahmed     Gamal                         1
..        ...        ...       ...                       ...
57       1005    Youssef     Halim                         3
58       1024    Youssef    Hegazy                        17
59       1061       Ziad     Fahmy                         8
60       1013       Ziad     Fouad                         2
61       1008       Ziad     Saleh                        19

[62 rows x 4 columns]

Question 2 : Which books match a choosen author pattern ?

In [1462]:
# Question 2 : Which books match a choosen author pattern ?
# I chose the authors with the beginning of M
Q2 = """SELECT author, title
From books
WHERE author Like 'M%'
"""

run(Q2)

           author                  title
0   Mahmoud Rafei   Storms and Sailboats
1   Mahmoud Rafei  The Clockwork Orchard
2  Mona Kholoussy   Notes from the Delta
3  Mona Kholoussy      The Glass Beehive

Question 3 : What are the most popular books ?

In [1463]:
# Question 3 : What are the most popular books ?

Q3 = """SELECT bookS.title,
               COUNT(checkouts.checkout_id) AS the_number_of_borrowings
FROM checkouts
JOIN books ON checkouts.book_id = books.book_id
GROUP BY books.title
ORDER BY the_number_of_borrowings DESC LIMIT 5
"""

run(Q3)

                    title  the_number_of_borrowings
0         The Silver Kite                        57
1   Fossils and Fireflies                        55
2  Circuits for Beginners                        46
3        Kites Over Cairo                        38
4    Storms and Sailboats                        25

Question 4 : What are the most effective active readers ?

In [1464]:
# Question 4 : What are the most effective active readers ?

Q4 = """SELECT members.member_id,
               members.first_name,
               members.last_name,
               COUNT(checkouts.checkout_id) AS the_number_of_borrowings
FROM checkouts
JOIN members ON checkouts.member_id = members.member_id
GROUP BY members.first_name, members.last_name
ORDER BY the_number_of_borrowings DESC LIMIT 10
"""

run(Q4)

   member_id first_name last_name  the_number_of_borrowings
0       1034        Aya     Wahba                        25
1       1044     Sherif     Saleh                        21
2       1008       Ziad     Saleh                        19
3       1027    Mostafa     Fouad                        18
4       1010       Nour     Nabil                        18
5       1065       Adam     Fahmy                        17
6       1018      Ahmed    Shafik                        17
7       1024    Youssef    Hegazy                        17
8       1030       Reem     Osman                        16
9       1047       Sara    Rashad                        16

Question 5 : What does a neghboorhood's activity look like futher back in time ?

In [1465]:
# Re-read members to get the updated data from the database
members = run("SELECT * FROM members")
neighborhoods_names = members["neighborhood"].value_counts()
print(f"The available neighborhoods count : \n {neighborhoods_names}")

The available neighborhoods count :
 neighborhood
Maadi         22
Nasr City     19
Heliopolis    18
Zamalek       14
Shubra         6
Nasr  City     1
Name: count, dtype: int64

I will clean the cities in the neighborhood column in members table inside the database to get all the cities

In [1466]:
members["neighborhood"] = members["neighborhood"].str.lower().str.title().str.strip()

print("Unique neighborhoods AFTER cleaning:")
print(members["neighborhood"].unique())

members.to_sql("members", conn, if_exists="replace", index=False)
print("\nDatabase 'members' table updated with cleaned neighborhoods.")

print('Value counts AFTER cleaning (from DataFrame):')
print(members["neighborhood"].value_counts())

Unique neighborhoods AFTER cleaning:
['Maadi' 'Nasr City' 'Nasr  City' 'Heliopolis' 'Zamalek' 'Shubra']

Database 'members' table updated with cleaned neighborhoods.
Value counts AFTER cleaning (from DataFrame):
neighborhood
Maadi         22
Nasr City     19
Heliopolis    18
Zamalek       14
Shubra         6
Nasr  City     1
Name: count, dtype: int64

In [1467]:
Q5 = """SELECT members.member_id,
               members.first_name,
               members.last_name,
               members.neighborhood,
               COUNT(checkouts.checkout_id) AS the_number_of_borrowings
FROM members
LEFT JOIN checkouts ON members.member_id = checkouts.member_id
WHERE members.neighborhood = 'Maadi'
GROUP BY members.member_id, members.first_name, members.last_name, members.neighborhood
ORDER BY the_number_of_borrowings DESC LIMIT 10 OFFSET 10
"""

run(Q5)

# The JOIN method has many types
# defalt --> INNER
# and the INNER JOIN couldn't join what I neeeded , so I used the LEFT JOIN

   member_id first_name last_name neighborhood  the_number_of_borrowings
0       1019    Mostafa     Wahba        Maadi                         3
1       1002      Fares     Saleh        Maadi                         2
2       1011      Menna     Halim        Maadi                         2
3       1013       Ziad     Fouad        Maadi                         2
4       1017       Adam      Badr        Maadi                         2
5       1001      Salma   Ibrahim        Maadi                         1
6       1006      Layla   Mansour        Maadi                         1
7       1009     Hassan     Saleh        Maadi                         1
8       1014     Habiba     Nabil        Maadi                         1
9       1004      Fares     Wahba        Maadi                         0

# Merging Process :

## Merging the members table and the checkouts table by python.

In [1468]:
# Merging the members table and the checkouts table by python.

merged_members_checkouts = members.merge(checkouts, on="member_id", how="left")
print(f"The Table :\n {merged_members_checkouts}")

The Table :
      member_id first_name last_name  grade neighborhood membership_status  \
0         1001      Salma   Ibrahim    8.0        Maadi            Active
1         1002      Fares     Saleh    9.0        Maadi            Active
2         1002      Fares     Saleh    9.0        Maadi            Active
3         1003     Bassel    Hegazy    6.0        Maadi            Active
4         1003     Bassel    Hegazy    6.0        Maadi            Active
..         ...        ...       ...    ...          ...               ...
404       1079       Rana     Osman    8.0       Shubra            Active
405       1079       Rana     Osman    8.0       Shubra            Active
406       1079       Rana     Osman    8.0       Shubra            Active
407       1080     Bassel     Wahba    9.0       Shubra            Active
408       1080     Bassel     Wahba    9.0       Shubra            Active

      join_date  checkout_id  book_id checkout_date return_date
0    2023-04-05       9025.0    525.0    2024-10-24  2024-11-07
1          None       9013.0    501.0    2024-02-16  2024-02-29
2          None       9095.0    507.0    2024-06-25  2024-07-07
3    2025-04-23       9051.0    513.0    2025-07-22  2025-08-18
4    2025-04-23       9068.0    501.0    2025-11-14  2025-12-03
..          ...          ...      ...           ...         ...
404  2024-10-27       9381.0    507.0    2025-05-30  2025-06-18
405  2024-10-27       9367.0    507.0    2024-03-19  2024-03-28
406  2024-10-27       9373.0    508.0    2024-03-20  2024-04-19
407  2023-12-28       9350.0    501.0    2025-06-22  2025-07-17
408  2023-12-28       9374.0    505.0    2024-08-05  2024-08-12

[409 rows x 11 columns]