<a href="https://colab.research.google.com/github/rghdzarad/31109170100123_Library/blob/main/31109170100123_Library_project_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **- The Name 👤: `Raghad Mohamed Abd El-Alim Malek Zarad`**
# **- The Student ID 🪪 : `EYOUTH-31109170100123`**
# **- The Project Name 📝 : `City Library After-School Program`**

**- The Project Description :**

* A city library runs an `After-School Program` for students. The program keeps track of two things: which students are members, and which books each member has borrowed.

* Every summer, the library also hosts an event called the `Reading Kickoff`. At this event, a student can borrow a book without using their membership card. Because there's no card involved, these borrowing records aren't stored with the rest — they're logged separately, on the library's website.

*  The program coordinator is now writing an `End-of-Summer Reading Report`, and needs the data to be accurate and complete before that report can be written.

**- 🎒 My Role in the Project :**

`I am the library's data assistant. I'm the one responsible for handing over the data in a shape someone else can actually work with.`

Now we will start solving the tasks.

- We have 3 tasks to do in the project :
* Task 1 : Data Gathering & combination `(Combined Data)`
* Task 2 : Data Integrity `(Cleaned Data)`
* Task 3 : Data Fairness & Version Control

# **Introduction to the system**

In [6]:
# the introduction
print("Welcome to the City Library After-School Program!")
print("This program keeps track of two things: which students are members, and which books each member has borrowed.")
print("Every summer, the library  hosts an event called the Reading Kickoff.")
print("At this event, a student can borrow a book without using their membership card.")
print("Because there's no card involved, these borrowing records aren't stored with the rest — they're logged separately, on the library's website.")
print("The program coordinator is now writing an End-of-Summer Reading Report, and needs the data to be accurate and complete before that report can be written.")
print()
print("Loading the system.........")

Welcome to the City Library After-School Program!
This program keeps track of two things: which students are members, and which books each member has borrowed.
Every summer, the library  hosts an event called the Reading Kickoff.
At this event, a student can borrow a book without using their membership card.
Because there's no card involved, these borrowing records aren't stored with the rest — they're logged separately, on the library's website.
The program coordinator is now writing an End-of-Summer Reading Report, and needs the data to be accurate and complete before that report can be written.

Loading the system.........

# **Checking the Cloud Machine**

In [7]:
# getting the info about the cloud machine and the python version
print("The Cloud Machine and the python version used : ")
import sys , platform
print(f"Python Version : {sys.version}")
print(f"Cloud Machine : {platform.node()}")

The Cloud Machine and the python version used :
Python Version : 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
Cloud Machine : 03b72a413a7f

# **Importing all the required libraries in python**

In [8]:
print("Importing the required libraries in python ......")
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3 as sql
from bs4 import BeautifulSoup
import requests
import json
import time

# importing the warnings library to prevent any errors from the library
import warnings
warnings.filterwarnings("ignore")
time.sleep(1.5)
print("The Libraries are loaded successfully :)")

Importing the required libraries in python ......
The Libraries are loaded successfully :)

### we will import the 3 sources of data to work on (db , json , html) to explore them  , answer the questions , and merge the 3 sources into 1 CSV File .

# **Task 1**

In [9]:
print("Loading the 3 sources of data............")
time.sleep(1)
print("The data is loaded successfully......")

Loading the 3 sources of data............
The data is loaded successfully......

### The SQL database

In [10]:
# the database connection
conn = sql.connect("/content/level3_final_project_library.db")

# function to ease working with SQL queries
def run(query):
    return pd.read_sql_query(query, conn)

# getting the tables from the database
members = run("SELECT * FROM members")
books = run("SELECT * FROM books")
checkouts = run("SELECT * FROM checkouts")

Exploring the Members Table

In [11]:
print("The tables in the database : ")
time.sleep(1)

The tables in the database :

In [12]:
print(f"The Table :\n {members}")
print()
print(f"The Dataset Shape : {members.shape}")
print()
print(f"The Dataset Info :\n {members.info()}")
print()
print(f"The statistical Description :\n {members.describe(include=np.number)}")
print()
print(f"The columns in the table : \n {members.columns.to_list()}")

The Table :
     member_id first_name last_name  grade neighborhood membership_status  \
0        1001      Salma   Ibrahim    8.0        Maadi            Active
1        1002      Fares     Saleh    9.0        Maadi            Active
2        1003     Bassel    Hegazy    6.0        Maadi            Active
3        1004      Fares     Wahba    7.0        Maadi          inactive
4        1005    Youssef     Halim    9.0        Maadi            Active
..        ...        ...       ...    ...          ...               ...
75       1076       Dina     Wahba    7.0       Shubra            Active
76       1077       Lina    Rashad    6.0       Shubra            Active
77       1078     Habiba     Osman    7.0       Shubra          INACTIVE
78       1079       Rana     Osman    8.0       Shubra            Active
79       1080     Bassel     Wahba    9.0       Shubra            Active

     join_date
0   2023-04-05
1         None
2   2025-04-23
3   2024-10-09
4   2024-05-05
..         ...
75  2025-12-13
76  2023-07-08
77  2023-08-05
78  2024-10-27
79  2023-12-28

[80 rows x 7 columns]

The Dataset Shape : (80, 7)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   member_id          80 non-null     int64
 1   first_name         80 non-null     object
 2   last_name          80 non-null     object
 3   grade              74 non-null     float64
 4   neighborhood       80 non-null     object
 5   membership_status  80 non-null     object
 6   join_date          76 non-null     object
dtypes: float64(1), int64(1), object(5)
memory usage: 4.5+ KB
The Dataset Info :
 None

The statistical Description :
        member_id      grade
count    80.0000  74.000000
mean   1040.5000   7.364865
std      23.2379   1.117413
min    1001.0000   6.000000
25%    1020.7500   6.000000
50%    1040.5000   7.000000
75%    1060.2500   8.000000
max    1080.0000   9.000000

The columns in the table :
 ['member_id', 'first_name', 'last_name', 'grade', 'neighborhood', 'membership_status', 'join_date']

Exploring the Books Table

In [13]:
print(f"The Table :\n {books}")
print()
print(f"The Dataset Shape : {books.shape}")
print()
print(f"The Dataset Info :\n {books.info()}")
print()
print(f"The statistical Description :\n {books.describe(include=np.number)}")
print()
print(f"The columns in the table : \n {books.columns.to_list()}")

The Table :
     book_id                    title          author
0       501          The Silver Kite   Amina Darwish
1       502           Desert Compass   Amina Darwish
2       503        The Lantern Maker    Adel Roushdy
3       504      Rooftop Astronomers    Adel Roushdy
4       505      Letters to the Nile       Aya Hafez
5       506      The Paper Boat Club       Aya Hafez
6       507    Fossils and Fireflies     Dalia Serry
7       508    The Quiet Observatory     Dalia Serry
8       509      Marbles and Mirrors     Diaa Sultan
9       510    The Missing Metronome     Diaa Sultan
10      511     Winter in Alexandria    Farida Anwar
11      512   The Cartographer's Cat    Farida Anwar
12      513   Circuits for Beginners    Galal Mounir
13      514    The Robot in Row Nine    Galal Mounir
14      515       Songs of the Oasis      Hoda Bakry
15      516  The Beekeeper's Almanac      Hoda Bakry
16      517  Shadows on the Corniche     Hani Nagati
17      518     The Ninth Lighthouse     Hani Nagati
18      519         Kites Over Cairo  Jasmine Wahdan
19      520     The Copper Telescope  Jasmine Wahdan
20      521    A Garden of Equations      Karim Elwy
21      522      The Puzzle Merchant      Karim Elwy
22      523    Footsteps in the Dust    Laila Shokry
23      524    The Weaver's Daughter    Laila Shokry
24      525     Storms and Sailboats   Mahmoud Rafei
25      526    The Clockwork Orchard   Mahmoud Rafei
26      527     Notes from the Delta  Mona Kholoussy
27      528        The Glass Beehive  Mona Kholoussy
28      529   Riddles of the Red Sea    Sara Tantawy
29      530        The Sandstone Key    Sara Tantawy
30      531    Voices in the Library     Samir Zohdy
31      532        The Last Bookmark     Samir Zohdy

The Dataset Shape : (32, 3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   book_id  32 non-null     int64
 1   title    32 non-null     object
 2   author   32 non-null     object
dtypes: int64(1), object(2)
memory usage: 900.0+ bytes
The Dataset Info :
 None

The statistical Description :
           book_id
count   32.000000
mean   516.500000
std      9.380832
min    501.000000
25%    508.750000
50%    516.500000
75%    524.250000
max    532.000000

The columns in the table :
 ['book_id', 'title', 'author']

Exploring the Checkouts Table

In [14]:
print(f"The Table :\n {checkouts}")
print()
print(f"The Dataset Shape : {checkouts.shape}")
print()
print(f"The Dataset Info :\n {checkouts.info()}")
print()
print(f"The statistical Description :\n {checkouts.describe(include=np.number)}")
print()
print(f"The columns in the table : \n {checkouts.columns.to_list()}")

The Table :
      checkout_id  member_id  book_id checkout_date return_date
0           9263       1047      517    2024-10-21  2024-11-07
1           9340       1072      513    2025-08-24  2025-09-01
2           9231       1053      523    2024-02-04  2024-02-16
3           9129       1032      513    2025-06-21  2025-06-29
4           9370       1079      511    2025-11-11  2025-12-03
..           ...        ...      ...           ...         ...
386         9232       1044      513    2025-05-26  2025-06-11
387         9084       1008      511    2024-06-27  2024-07-22
388         9116       1024      519    2025-01-10  2025-02-09
389         9352       1076      501    2025-02-02        None
390         9246       1044      529    2025-06-25  2025-07-04

[391 rows x 5 columns]

The Dataset Shape : (391, 5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 391 entries, 0 to 390
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   checkout_id    391 non-null    int64
 1   member_id      391 non-null    int64
 2   book_id        391 non-null    int64
 3   checkout_date  391 non-null    object
 4   return_date    326 non-null    object
dtypes: int64(3), object(2)
memory usage: 15.4+ KB
The Dataset Info :
 None

The statistical Description :
        checkout_id    member_id     book_id
count   391.000000   391.000000  391.000000
mean   9192.611253  1039.841432  513.271100
std     110.279771    22.925977    8.982785
min    9001.000000  1001.000000  501.000000
25%    9097.500000  1020.000000  507.000000
50%    9193.000000  1034.000000  513.000000
75%    9287.500000  1060.500000  519.000000
max    9383.000000  1080.000000  532.000000

The columns in the table :
 ['checkout_id', 'member_id', 'book_id', 'checkout_date', 'return_date']

### The json file

In [15]:
print("The data in the json file : ")
time.sleep(1.3)

The data in the json file :

In [16]:
json_df = pd.read_json("/content/level3_final_project_book_catalog.json")
print(f"The Table :\n {json_df}")
print()
print(f"The Dataset Shape : {json_df.shape}")
print()
print(f"The Dataset Info :\n {json_df.info()}")
print()
print(f"The statistical Description :\n {json_df.describe(include=np.number)}")
print()
print(f"The columns in the table : \n {json_df.columns.to_list()}")

The Table :
     book_id            genre  pages  publication_year            publisher
0       501        Adventure    128            2017.0           Nile Press
1       502        Adventure    109            2018.0          Delta House
2       503       Historical    259               NaN           Nile Press
3       504          Science    319            2009.0  Cairo Young Readers
4       505       Historical    216            2024.0          Oasis Books
5       506       Friendship    183               NaN           Nile Press
6       507          Science    160            2024.0           Nile Press
7       508          Science    306            2011.0          Oasis Books
8       509          Mystery    221            2011.0           Nile Press
9       510          Mystery    134            2013.0  Cairo Young Readers
10      511       Historical    117            2016.0           Nile Press
11      512        Adventure    238            2022.0          Delta House
12      513          Science    294            2021.0          Oasis Books
13      514  Science Fiction    328            2023.0  Cairo Young Readers
14      515           Poetry    316            2022.0  Cairo Young Readers
15      516           Nature    241            2010.0           Nile Press
16      517          Mystery    338            2015.0          Delta House
17      518        Adventure    163            2011.0          Delta House
18      519       Friendship    157            2014.0           Nile Press
19      520  Science Fiction    136            2009.0          Oasis Books
20      521          Science    211            2024.0  Cairo Young Readers
21      522          Mystery    104            2016.0  Cairo Young Readers
22      523       Historical    276            2018.0          Oasis Books
23      524       Historical    114            2016.0  Cairo Young Readers
24      525        Adventure    297            2015.0          Oasis Books
25      526  Science Fiction    125            2016.0          Delta House
26      527           Nature    328            2017.0          Delta House
27      528           Nature    114            2010.0          Delta House
28      529          Mystery    298               NaN  Cairo Young Readers
29      530        Adventure    208            2012.0          Oasis Books
30      531       Friendship    272            2018.0          Oasis Books
31      532       Friendship    337            2017.0          Oasis Books

The Dataset Shape : (32, 5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   book_id           32 non-null     int64
 1   genre             32 non-null     object
 2   pages             32 non-null     int64
 3   publication_year  29 non-null     float64
 4   publisher         32 non-null     object
dtypes: float64(1), int64(2), object(2)
memory usage: 1.4+ KB
The Dataset Info :
 None

The statistical Description :
           book_id       pages  publication_year
count   32.000000   32.000000         29.000000
mean   516.500000  220.218750       2016.172414
std      9.380832   81.556525          4.736401
min    501.000000  104.000000       2009.000000
25%    508.750000  135.500000       2012.000000
50%    516.500000  218.500000       2016.000000
75%    524.250000  297.250000       2018.000000
max    532.000000  338.000000       2024.000000

The columns in the table :
 ['book_id', 'genre', 'pages', 'publication_year', 'publisher']

### The html file (website)

In [17]:
print("The HTML table : ")
time.sleep(1.5)

The HTML table :

In [18]:
# getting the data from the website
html_tables = pd.read_html("/content/level3_final_project_event_signups.html")
the_table = html_tables[0]

#  renaming the columns of the html tables to help in the merging process
the_table = the_table.rename(columns={"Member ID" : "member_id"})
the_table = the_table.rename(columns={"Book ID" : "book_id" })
the_table = the_table.rename(columns={"Checkout Date" : "checkout_date"})

# simple inspection process
print(f"The Table :\n {the_table}")
print()
print(f"The Dataset Shape : {the_table.shape}")
print()
print(f"The Dataset Info :\n {the_table.info()}")
print()
print(f"The statistical Description :\n {the_table.describe(include=np.number)}")
print()
print(f"The columns in the table : \n {the_table.columns.to_list()}")
print()

The Table :
     member_id  book_id checkout_date
0        1026      522    2025-07-11
1        1049      520    2025-07-11
2        1062      525    2025-07-05
3        1065      520    2025-07-07
4        1104      515    2025-07-07
5        1009      503    2025-07-09
6        1063      522    2025-07-07
7        1022      511    2025-07-12
8        1029      523    2025-07-09
9        1201      509    2025-07-10
10       1005      513    2025-07-10
11       1104      526    2025-07-05
12       1058      518    2025-07-08
13       1002      521    2025-07-08
14       1150      530    2025-07-10
15       1041      504    2025-07-05
16       1055      526    2025-07-11
17       1061      513    2025-07-06
18       1012      509    2025-07-11
19       1007      510    2025-07-07
20       1073      530    2025-07-07
21       1003      501    2025-07-08
22       1017      507    2025-07-11
23       1061      504    2025-07-06
24       1201      523    2025-07-08
25       1041      512    2025-07-06

The Dataset Shape : (26, 3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   member_id      26 non-null     int64
 1   book_id        26 non-null     int64
 2   checkout_date  26 non-null     object
dtypes: int64(2), object(1)
memory usage: 756.0+ bytes
The Dataset Info :
 None

The statistical Description :
          member_id     book_id
count    26.000000   26.000000
mean   1058.500000  516.038462
std      54.961259    8.627773
min    1002.000000  501.000000
25%    1018.250000  509.250000
50%    1052.000000  516.500000
75%    1064.500000  522.750000
max    1201.000000  530.000000

The columns in the table :
 ['member_id', 'book_id', 'checkout_date']

Now , We will make a copy of the original datasets to return to them if needed

In [19]:
print("Making a copy of the original data to return to it when needed.........")
# the database copy
members_copy = members.copy()
books_copy = books.copy()
checkouts_copy = checkouts.copy()

# the json copy
json_df_copy = json_df.copy()

# the html copy
the_table_copy = the_table.copy()
time.sleep(1.5)
print("The coping process is completed successfull :)")

Making a copy of the original data to return to it when needed.........
The coping process is completed successfull :)

## **Answering the 5 Question :**

In [20]:
print("Asking the questions to the SQL database and getting the answers.....")
time.sleep(1)
print("asking......")
time.sleep(0.5)
print("getting the answer.....")
time.sleep(0.5)
print("Processing.......")
time.sleep(1.5)
print("the process was completed successfully :) ")

Asking the questions to the SQL database and getting the answers.....
asking......
getting the answer.....
Processing.......
the process was completed successfully :)

Question 1 : How much is each member borrowing ?

In [21]:
# Question 1: How much is each member borrowing?
print("Question 1: How much is each member borrowing?")
time.sleep(0.5)
print("The answer : ")
print()
Q1 = """SELECT members.member_id,
                  members.first_name,
                  members.last_name,
                  COUNT(checkouts.checkout_id) AS the_number_of_borrowings
FROM checkouts
JOIN members ON checkouts.member_id = members.member_id
GROUP BY members.first_name, members.last_name
ORDER BY the_number_of_borrowings ASC
"""

run(Q1)

Question 1: How much is each member borrowing?
The answer :

    member_id first_name last_name  the_number_of_borrowings
0        1049      Ahmed     Gamal                         1
1        1031        Ali     Fahmy                         1
2        1046       Amir     Fouad                         1
3        1014     Habiba     Nabil                         1
4        1023     Hassan    Rashad                         1
..        ...        ...       ...                       ...
57       1027    Mostafa     Fouad                        18
58       1010       Nour     Nabil                        18
59       1008       Ziad     Saleh                        19
60       1044     Sherif     Saleh                        21
61       1034        Aya     Wahba                        25

[62 rows x 4 columns]

Question 2 : Which books match a choosen author pattern ?

In [22]:
# Question 2 : Which books match a choosen author pattern ?
# I chose the authors with the beginning of M

print("Question 2 : Which books match a choosen author pattern ?")
time.sleep(0.5)
print("I chose the authors with the beginning of M")
time.sleep(1)
print("The answer : ")
print()
Q2 = """SELECT author, title
From books
WHERE author Like 'M%'
"""

run(Q2)

Question 2 : Which books match a choosen author pattern ?
I chose the authors with the beginning of M
The answer :

           author                  title
0   Mahmoud Rafei   Storms and Sailboats
1   Mahmoud Rafei  The Clockwork Orchard
2  Mona Kholoussy   Notes from the Delta
3  Mona Kholoussy      The Glass Beehive

Question 3 : What are the most popular books ?

In [23]:
# Question 3 : What are the most popular books ?
print("Question 3 : What are the most popular books ?")
time.sleep(0.5)
print("The answer : ")
print()
Q3 = """SELECT bookS.title,
               COUNT(checkouts.checkout_id) AS the_number_of_borrowings
FROM checkouts
JOIN books ON checkouts.book_id = books.book_id
GROUP BY books.title
ORDER BY the_number_of_borrowings DESC LIMIT 5
"""

run(Q3)

Question 3 : What are the most popular books ?
The answer :

                    title  the_number_of_borrowings
0         The Silver Kite                        57
1   Fossils and Fireflies                        55
2  Circuits for Beginners                        46
3        Kites Over Cairo                        38
4    Storms and Sailboats                        25

Question 4 : What are the most effective active readers ?

In [24]:
# Question 4 : What are the most effective active readers ?
print("Question 4 : What are the most effective active readers ?")
time.sleep(0.5)
print("The answer : ")
print()
Q4 = """SELECT members.member_id,
               members.first_name,
               members.last_name,
               COUNT(checkouts.checkout_id) AS the_number_of_borrowings
FROM checkouts
JOIN members ON checkouts.member_id = members.member_id
GROUP BY members.first_name, members.last_name
ORDER BY the_number_of_borrowings DESC LIMIT 10
"""

run(Q4)

Question 4 : What are the most effective active readers ?
The answer :

   member_id first_name last_name  the_number_of_borrowings
0       1034        Aya     Wahba                        25
1       1044     Sherif     Saleh                        21
2       1008       Ziad     Saleh                        19
3       1027    Mostafa     Fouad                        18
4       1010       Nour     Nabil                        18
5       1065       Adam     Fahmy                        17
6       1018      Ahmed    Shafik                        17
7       1024    Youssef    Hegazy                        17
8       1030       Reem     Osman                        16
9       1047       Sara    Rashad                        16

 Question 5 : What does a neghboorhood's activity look like futher back in time ? (Maadi)

In [25]:
# Re-read members to get the number of unique values for each neighborhood and choose 1 neighbourhood
members = run("SELECT * FROM members")
neighborhoods_names = members["neighborhood"].value_counts()
print(f"The available neighborhoods count : \n {neighborhoods_names}")

The available neighborhoods count :
 neighborhood
Maadi         20
Nasr City     18
Heliopolis    16
Zamalek       13
Shubra         6
Maadi          2
HELIOPOLIS     2
Nasr  City     1
NASR CITY      1
zamalek        1
Name: count, dtype: int64

I will clean the cities in the neighborhood column in members table inside the database to get all the cities

In [26]:
# cleaning the column of the neighbourhood by giving them the right format
members["neighborhood"] = members["neighborhood"].str.lower().str.title().str.strip()

print("Unique neighborhoods AFTER cleaning:")
print(members["neighborhood"].unique())

members.to_sql("members", conn, if_exists="replace", index=False)
print("\nDatabase 'members' table updated with cleaned neighbourhoods")
print(members["neighborhood"].unique())

members.to_sql("members", conn, if_exists="replace", index=False)
print("\nDatabase 'members' table updated with cleaned neighborhoods.")

print('Value counts AFTER cleaning (from DataFrame):')
print(members["neighborhood"].value_counts())

Unique neighborhoods AFTER cleaning:
['Maadi' 'Nasr City' 'Nasr  City' 'Heliopolis' 'Zamalek' 'Shubra']

Database 'members' table updated with cleaned neighbourhoods
['Maadi' 'Nasr City' 'Nasr  City' 'Heliopolis' 'Zamalek' 'Shubra']

Database 'members' table updated with cleaned neighborhoods.
Value counts AFTER cleaning (from DataFrame):
neighborhood
Maadi         22
Nasr City     19
Heliopolis    18
Zamalek       14
Shubra         6
Nasr  City     1
Name: count, dtype: int64

In [27]:
print("Question 5 : What does a neghboorhood's activity look like futher back in time ? (Maadi)")
time.sleep(1)
print("The answer : ")
print()
Q5 = """SELECT members.member_id,
               members.first_name,
               members.last_name,
               members.neighborhood,
               COUNT(checkouts.checkout_id) AS the_number_of_borrowings
FROM members
LEFT JOIN checkouts ON members.member_id = checkouts.member_id
WHERE members.neighborhood = 'Maadi'
GROUP BY members.member_id, members.first_name, members.last_name, members.neighborhood
ORDER BY the_number_of_borrowings DESC LIMIT 10 OFFSET 10
"""

run(Q5)

# The JOIN method has many types
# defalt --> INNER
# and the INNER JOIN couldn't join what I neeeded , so I used the LEFT JOIN

Question 5 : What does a neghboorhood's activity look like futher back in time ? (Maadi)
The answer :

   member_id first_name last_name neighborhood  the_number_of_borrowings
0       1019    Mostafa     Wahba        Maadi                         3
1       1002      Fares     Saleh        Maadi                         2
2       1011      Menna     Halim        Maadi                         2
3       1013       Ziad     Fouad        Maadi                         2
4       1017       Adam      Badr        Maadi                         2
5       1001      Salma   Ibrahim        Maadi                         1
6       1006      Layla   Mansour        Maadi                         1
7       1009     Hassan     Saleh        Maadi                         1
8       1014     Habiba     Nabil        Maadi                         1
9       1004      Fares     Wahba        Maadi                         0

# Merging Process :

## Merging the members table and the checkouts table by python.

In [28]:
# Merging the members table and the checkouts table by python.

print("merging the 3 sources......")
time.sleep(1)
print("wait a little bit.......")
time.sleep(1.5)
print("the process was completed successfully :)")
merged_members_checkouts_sql = members.merge(checkouts, on="member_id", how="left")
print(f"The Table :\n {merged_members_checkouts_sql}")

merging the 3 sources......
wait a little bit.......
the process was completed successfully :)
The Table :
      member_id first_name last_name  grade neighborhood membership_status  \
0         1001      Salma   Ibrahim    8.0        Maadi            Active
1         1002      Fares     Saleh    9.0        Maadi            Active
2         1002      Fares     Saleh    9.0        Maadi            Active
3         1003     Bassel    Hegazy    6.0        Maadi            Active
4         1003     Bassel    Hegazy    6.0        Maadi            Active
..         ...        ...       ...    ...          ...               ...
404       1079       Rana     Osman    8.0       Shubra            Active
405       1079       Rana     Osman    8.0       Shubra            Active
406       1079       Rana     Osman    8.0       Shubra            Active
407       1080     Bassel     Wahba    9.0       Shubra            Active
408       1080     Bassel     Wahba    9.0       Shubra            Active

      join_date  checkout_id  book_id checkout_date return_date
0    2023-04-05       9025.0    525.0    2024-10-24  2024-11-07
1          None       9013.0    501.0    2024-02-16  2024-02-29
2          None       9095.0    507.0    2024-06-25  2024-07-07
3    2025-04-23       9051.0    513.0    2025-07-22  2025-08-18
4    2025-04-23       9068.0    501.0    2025-11-14  2025-12-03
..          ...          ...      ...           ...         ...
404  2024-10-27       9381.0    507.0    2025-05-30  2025-06-18
405  2024-10-27       9367.0    507.0    2024-03-19  2024-03-28
406  2024-10-27       9373.0    508.0    2024-03-20  2024-04-19
407  2023-12-28       9350.0    501.0    2025-06-22  2025-07-17
408  2023-12-28       9374.0    505.0    2024-08-05  2024-08-12

[409 rows x 11 columns]

## Merging the merged dataset `(sql)` with the `json file` and the `html table`.

first : the json file

In [29]:
sql_json_merged = merged_members_checkouts_sql.merge(json_df , on = "book_id" , how = "left")
print(f"The Table :\n {sql_json_merged}")
print()
# simple inspection process
print(f"The 1st 5 rows inside the merged table : \n {sql_json_merged.head()}")
print()
print(f"The Dataset Shape : {sql_json_merged.shape}")
print()
print(f"The Dataset Info :\n {sql_json_merged.info()}")
print()
print(f"The statistical Description :\n {sql_json_merged.describe(include=np.number)}")
print()
print(f"The columns inside the merged table : \n {sql_json_merged.columns.to_list()}")

The Table :
      member_id first_name last_name  grade neighborhood membership_status  \
0         1001      Salma   Ibrahim    8.0        Maadi            Active
1         1002      Fares     Saleh    9.0        Maadi            Active
2         1002      Fares     Saleh    9.0        Maadi            Active
3         1003     Bassel    Hegazy    6.0        Maadi            Active
4         1003     Bassel    Hegazy    6.0        Maadi            Active
..         ...        ...       ...    ...          ...               ...
404       1079       Rana     Osman    8.0       Shubra            Active
405       1079       Rana     Osman    8.0       Shubra            Active
406       1079       Rana     Osman    8.0       Shubra            Active
407       1080     Bassel     Wahba    9.0       Shubra            Active
408       1080     Bassel     Wahba    9.0       Shubra            Active

      join_date  checkout_id  book_id checkout_date return_date       genre  \
0    2023-04-05       9025.0    525.0    2024-10-24  2024-11-07   Adventure
1          None       9013.0    501.0    2024-02-16  2024-02-29   Adventure
2          None       9095.0    507.0    2024-06-25  2024-07-07     Science
3    2025-04-23       9051.0    513.0    2025-07-22  2025-08-18     Science
4    2025-04-23       9068.0    501.0    2025-11-14  2025-12-03   Adventure
..          ...          ...      ...           ...         ...         ...
404  2024-10-27       9381.0    507.0    2025-05-30  2025-06-18     Science
405  2024-10-27       9367.0    507.0    2024-03-19  2024-03-28     Science
406  2024-10-27       9373.0    508.0    2024-03-20  2024-04-19     Science
407  2023-12-28       9350.0    501.0    2025-06-22  2025-07-17   Adventure
408  2023-12-28       9374.0    505.0    2024-08-05  2024-08-12  Historical

     pages  publication_year    publisher
0    297.0            2015.0  Oasis Books
1    128.0            2017.0   Nile Press
2    160.0            2024.0   Nile Press
3    294.0            2021.0  Oasis Books
4    128.0            2017.0   Nile Press
..     ...               ...          ...
404  160.0            2024.0   Nile Press
405  160.0            2024.0   Nile Press
406  306.0            2011.0  Oasis Books
407  128.0            2017.0   Nile Press
408  216.0            2024.0  Oasis Books

[409 rows x 15 columns]

The 1st 5 rows inside the merged table :
    member_id first_name last_name  grade neighborhood membership_status  \
0       1001      Salma   Ibrahim    8.0        Maadi            Active
1       1002      Fares     Saleh    9.0        Maadi            Active
2       1002      Fares     Saleh    9.0        Maadi            Active
3       1003     Bassel    Hegazy    6.0        Maadi            Active
4       1003     Bassel    Hegazy    6.0        Maadi            Active

    join_date  checkout_id  book_id checkout_date return_date      genre  \
0  2023-04-05       9025.0    525.0    2024-10-24  2024-11-07  Adventure
1        None       9013.0    501.0    2024-02-16  2024-02-29  Adventure
2        None       9095.0    507.0    2024-06-25  2024-07-07    Science
3  2025-04-23       9051.0    513.0    2025-07-22  2025-08-18    Science
4  2025-04-23       9068.0    501.0    2025-11-14  2025-12-03  Adventure

   pages  publication_year    publisher
0  297.0            2015.0  Oasis Books
1  128.0            2017.0   Nile Press
2  160.0            2024.0   Nile Press
3  294.0            2021.0  Oasis Books
4  128.0            2017.0   Nile Press

The Dataset Shape : (409, 15)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 409 entries, 0 to 408
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   member_id          409 non-null    int64
 1   first_name         409 non-null    object
 2   last_name          409 non-null    object
 3   grade              371 non-null    float64
 4   neighborhood       409 non-null    object
 5   membership_status  409 non-null    object
 6   join_date          403 non-null    object
 7   checkout_id        391 non-null    float64
 8   book_id            391 non-null    float64
 9   checkout_date      391 non-null    object
 10  return_date        326 non-null    object
 11  genre              391 non-null    object
 12  pages              391 non-null    float64
 13  publication_year   357 non-null    float64
 14  publisher          391 non-null    object
dtypes: float64(5), int64(1), object(9)
memory usage: 48.1+ KB
The Dataset Info :
 None

The statistical Description :
          member_id       grade  checkout_id     book_id       pages  \
count   409.000000  371.000000   391.000000  391.000000  391.000000
mean   1040.012225    7.560647  9192.611253  513.271100  201.969309
std      22.815272    1.152419   110.279771    8.982785   73.974175
min    1001.000000    6.000000  9001.000000  501.000000  104.000000
25%    1020.000000    7.000000  9097.500000  507.000000  134.000000
50%    1036.000000    8.000000  9193.000000  513.000000  160.000000
75%    1061.000000    9.000000  9287.500000  519.000000  294.000000
max    1080.000000    9.000000  9383.000000  532.000000  338.000000

       publication_year
count        357.000000
mean        2017.560224
std            4.523334
min         2009.000000
25%         2014.000000
50%         2017.000000
75%         2021.000000
max         2024.000000

The columns inside the merged table :
 ['member_id', 'first_name', 'last_name', 'grade', 'neighborhood', 'membership_status', 'join_date', 'checkout_id', 'book_id', 'checkout_date', 'return_date', 'genre', 'pages', 'publication_year', 'publisher']

Before merging between 2 different tables with the purpose of `html table` and the `merged SQL JSON dataset`, we must give the necessary columns the right type to prevent any outliers, missing values or errors during the merging process.

In [30]:
# changing the types of essencial columns temporarily for the merging process; then I will give them the right type

# the merged sql json dataset
sql_json_merged["member_id"] = sql_json_merged["member_id"].astype(int)
# Use nullable integer type for book_id to get it to the integer type without any proplems or errors during the merging process because of the missing values (nan).
sql_json_merged["book_id"] = sql_json_merged["book_id"].astype(pd.Int64Dtype())
sql_json_merged["checkout_date"] = pd.to_datetime(sql_json_merged["checkout_date"] , format = "mixed")

# the html table
the_table["member_id"] = the_table["member_id"].astype(int)
the_table["book_id"] = the_table["book_id"].astype(int)
the_table["checkout_date"] = pd.to_datetime(the_table["checkout_date"] , format = "mixed")

second : the html table

In [31]:
# the final merging process :)

the_complete_merged_dataset = sql_json_merged.merge(the_table , on = ["member_id" , "book_id" , "checkout_date"] , how = "outer")
# I used how = "outer" instead of keep = "left" to keep the columns and all the members and prevent any accidental deletion during the merging process or any missing membermembers.
print(f"The Table :\n {the_complete_merged_dataset}")

The Table :
      member_id first_name last_name  grade neighborhood membership_status  \
0         1001      Salma   Ibrahim    8.0        Maadi            Active
1         1002      Fares     Saleh    9.0        Maadi            Active
2         1002      Fares     Saleh    9.0        Maadi            Active
3         1002        NaN       NaN    NaN          NaN               NaN
4         1003     Bassel    Hegazy    6.0        Maadi            Active
..         ...        ...       ...    ...          ...               ...
430       1104        NaN       NaN    NaN          NaN               NaN
431       1104        NaN       NaN    NaN          NaN               NaN
432       1150        NaN       NaN    NaN          NaN               NaN
433       1201        NaN       NaN    NaN          NaN               NaN
434       1201        NaN       NaN    NaN          NaN               NaN

      join_date  checkout_id  book_id checkout_date return_date      genre  \
0    2023-04-05       9025.0      525    2024-10-24  2024-11-07  Adventure
1          None       9013.0      501    2024-02-16  2024-02-29  Adventure
2          None       9095.0      507    2024-06-25  2024-07-07    Science
3           NaN          NaN      521    2025-07-08         NaN        NaN
4    2025-04-23       9074.0      501    2024-06-19  2024-07-06  Adventure
..          ...          ...      ...           ...         ...        ...
430         NaN          NaN      515    2025-07-07         NaN        NaN
431         NaN          NaN      526    2025-07-05         NaN        NaN
432         NaN          NaN      530    2025-07-10         NaN        NaN
433         NaN          NaN      509    2025-07-10         NaN        NaN
434         NaN          NaN      523    2025-07-08         NaN        NaN

     pages  publication_year    publisher
0    297.0            2015.0  Oasis Books
1    128.0            2017.0   Nile Press
2    160.0            2024.0   Nile Press
3      NaN               NaN          NaN
4    128.0            2017.0   Nile Press
..     ...               ...          ...
430    NaN               NaN          NaN
431    NaN               NaN          NaN
432    NaN               NaN          NaN
433    NaN               NaN          NaN
434    NaN               NaN          NaN

[435 rows x 15 columns]

## Simple inspection for the combined dataset before turning it to a CSV file

In [32]:
print("Small inspectation for the combined dataset.........")
time.sleep(0.5)
print("Inspecting..........")
time.sleep(0.5)
print("The inspection process was completed successfully :)")
print()
print(f"The Dataset : \n {the_complete_merged_dataset}")
print()
print(f"The Dataset shape : {the_complete_merged_dataset.shape}")
print()
print(f"The Dataset info : \n {the_complete_merged_dataset.info()}")
print()
print(f"The statistical Description : \n {the_complete_merged_dataset.describe(include=np.number)}")
print()
print(f"The columns inside the merged table : \n {the_complete_merged_dataset.columns.to_list()}")

Small inspectation for the combined dataset.........
Inspecting..........
The inspection process was completed successfully :)

The Dataset :
      member_id first_name last_name  grade neighborhood membership_status  \
0         1001      Salma   Ibrahim    8.0        Maadi            Active
1         1002      Fares     Saleh    9.0        Maadi            Active
2         1002      Fares     Saleh    9.0        Maadi            Active
3         1002        NaN       NaN    NaN          NaN               NaN
4         1003     Bassel    Hegazy    6.0        Maadi            Active
..         ...        ...       ...    ...          ...               ...
430       1104        NaN       NaN    NaN          NaN               NaN
431       1104        NaN       NaN    NaN          NaN               NaN
432       1150        NaN       NaN    NaN          NaN               NaN
433       1201        NaN       NaN    NaN          NaN               NaN
434       1201        NaN       NaN    NaN          NaN               NaN

      join_date  checkout_id  book_id checkout_date return_date      genre  \
0    2023-04-05       9025.0      525    2024-10-24  2024-11-07  Adventure
1          None       9013.0      501    2024-02-16  2024-02-29  Adventure
2          None       9095.0      507    2024-06-25  2024-07-07    Science
3           NaN          NaN      521    2025-07-08         NaN        NaN
4    2025-04-23       9074.0      501    2024-06-19  2024-07-06  Adventure
..          ...          ...      ...           ...         ...        ...
430         NaN          NaN      515    2025-07-07         NaN        NaN
431         NaN          NaN      526    2025-07-05         NaN        NaN
432         NaN          NaN      530    2025-07-10         NaN        NaN
433         NaN          NaN      509    2025-07-10         NaN        NaN
434         NaN          NaN      523    2025-07-08         NaN        NaN

     pages  publication_year    publisher
0    297.0            2015.0  Oasis Books
1    128.0            2017.0   Nile Press
2    160.0            2024.0   Nile Press
3      NaN               NaN          NaN
4    128.0            2017.0   Nile Press
..     ...               ...          ...
430    NaN               NaN          NaN
431    NaN               NaN          NaN
432    NaN               NaN          NaN
433    NaN               NaN          NaN
434    NaN               NaN          NaN

[435 rows x 15 columns]

The Dataset shape : (435, 15)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   member_id          435 non-null    int64
 1   first_name         409 non-null    object
 2   last_name          409 non-null    object
 3   grade              371 non-null    float64
 4   neighborhood       409 non-null    object
 5   membership_status  409 non-null    object
 6   join_date          403 non-null    object
 7   checkout_id        391 non-null    float64
 8   book_id            417 non-null    Int64
 9   checkout_date      417 non-null    datetime64[ns]
 10  return_date        326 non-null    object
 11  genre              391 non-null    object
 12  pages              391 non-null    float64
 13  publication_year   357 non-null    float64
 14  publisher          391 non-null    object
dtypes: Int64(1), datetime64[ns](1), float64(4), int64(1), object(8)
memory usage: 51.5+ KB
The Dataset info :
 None

The statistical Description :
          member_id       grade  checkout_id     book_id       pages  \
count   435.000000  371.000000   391.000000       417.0  391.000000
mean   1041.117241    7.560647  9192.611253  513.443645  201.969309
std      26.126819    1.152419   110.279771    8.976053   73.974175
min    1001.000000    6.000000  9001.000000       501.0  104.000000
25%    1020.000000    7.000000  9097.500000       507.0  134.000000
50%    1038.000000    8.000000  9193.000000       513.0  160.000000
75%    1061.000000    9.000000  9287.500000       519.0  294.000000
max    1201.000000    9.000000  9383.000000       532.0  338.000000

       publication_year
count        357.000000
mean        2017.560224
std            4.523334
min         2009.000000
25%         2014.000000
50%         2017.000000
75%         2021.000000
max         2024.000000

The columns inside the merged table :
 ['member_id', 'first_name', 'last_name', 'grade', 'neighborhood', 'membership_status', 'join_date', 'checkout_id', 'book_id', 'checkout_date', 'return_date', 'genre', 'pages', 'publication_year', 'publisher']

## Turning the dataset into a CSV file that can be downloaded

In [33]:
# The converting process
print("Converting to a csv file......")
time.sleep(1)
the_complete_merged_dataset.to_csv("31109170100123_Library_task1_combined_data.csv" , index = False)
print("The converting process was completed successfully :)")
time.sleep(0.5)
print("We successfully finished Task 1")

Converting to a csv file......
The converting process was completed successfully :)
We successfully finished Task 1

# **Before proceeding to task 2, I will outline the steps I completed in task 1 to ensure transparency in my process.**

## Initially, I imported the necessary Python libraries. I then loaded three data sources: `an SQL database, an HTML website, and a JSON file.` Using the `sqlite3 library`, I addressed the five questions by executing database queries. Subsequently, I merged the members and checkouts tables, followed by integration with the `JSON dataset` and, finally, the `HTML table` dataset.

## Additionally, I obtained the `HTML table` from the website through `WEB SCRAPING` and read it using the `pd.read_html()` function.

# **Now , let's talk about APIs ans web scraping**

# **What is the difference between the API and web scraping?**
To begin with, Application Programming Interfaces `(APIs)` represent 2 fundamentally different approaches to data acquisition (data collection from websites). APIs provide a structured and efficient mechanism for data transfer, enabling direct access to specified data fields and collecting them in an organised, machine-readable format `(JSON files)` with great speed. This ensures high reliability, but it is limited, and you can't collect all the data `(limited data access by the API provider)`. You must also respect the website's terms and policies `(robot.txt)` and avoid making too many requests, so the website server doesn't stop.


On the other hand, web scraping involves extracting data yourself programmatically `(parsing the entire content of the web pages, especially HTML tables)`. While web scraping offers broader access to any publicly visible data, it is less efficient, prone to data quality issues due to inconsistent formatting, and highly sensitive to changes in website structure. For the library case, I used web scraping because the website for the reading kick-off event doesn't have an API, so I used the pandas function `pd.read_html()`.

# **Now, let's get to task 2 :)**

# **Task 2 : Data Integrity**

In [34]:
# imported the Combined CSV file
print("Getting the Merged dataset.......")
df = pd.read_csv("/content/31109170100123_Library_task1_combined_data.csv")
time.sleep(1)
print("The process was completed successfully :)")

Getting the Merged dataset.......
The process was completed successfully :)

# **Inspecting the CSV file dataset**

In [35]:
print("Inspecting the dataset.........")
time.sleep(0.5)
print("Loading the CSV file........")
time.sleep(0.5)
print("The CSV was loaded successfully :)")
time.sleep(0.5)
print("Continue the inspecting process.......")
time.sleep(1)
print("The process was completed successfully :)")
print("The Dataset : ")
print()
print(f"The Dataset : \n {df}")
print()
print(f"The 1st 5 rows in the dataset --> \n {df.head(n=5)}")
print()
print(f"The last 5 rows in the dataset --> \n {df.tail(n=5)}")
print()
print(f"The dataset shape --> {df.shape}")
print()
print(f"The dataset size --> {df.size}")
print()
print(f"The dataset info --> \n {df.info()}")
print()
print(f"The statistical description of the dataset --> \n {df.describe(include=np.number)}")
print()
print(f"The columns inside the dataset --> \n {df.columns.to_list()}")
print()
print(f"The number of duplicated rows --> {df.duplicated().sum()}")
print()
duplicated = df[df.duplicated()]
print(f"The duplicated rows --> \n {duplicated}")
print(f"The number of missing values in the dataset for each column --> \n {df.isnull().sum()}")
print()
print(f"The types of the columns in the dataset --> \n {df.dtypes}")

Inspecting the dataset.........
Loading the CSV file........
The CSV was loaded successfully :)
Continue the inspecting process.......
The process was completed successfully :)
The Dataset :

The Dataset :
      member_id first_name last_name  grade neighborhood membership_status  \
0         1001      Salma   Ibrahim    8.0        Maadi            Active
1         1002      Fares     Saleh    9.0        Maadi            Active
2         1002      Fares     Saleh    9.0        Maadi            Active
3         1002        NaN       NaN    NaN          NaN               NaN
4         1003     Bassel    Hegazy    6.0        Maadi            Active
..         ...        ...       ...    ...          ...               ...
430       1104        NaN       NaN    NaN          NaN               NaN
431       1104        NaN       NaN    NaN          NaN               NaN
432       1150        NaN       NaN    NaN          NaN               NaN
433       1201        NaN       NaN    NaN          NaN               NaN
434       1201        NaN       NaN    NaN          NaN               NaN

      join_date  checkout_id  book_id checkout_date return_date      genre  \
0    2023-04-05       9025.0    525.0    2024-10-24  2024-11-07  Adventure
1           NaN       9013.0    501.0    2024-02-16  2024-02-29  Adventure
2           NaN       9095.0    507.0    2024-06-25  2024-07-07    Science
3           NaN          NaN    521.0    2025-07-08         NaN        NaN
4    2025-04-23       9074.0    501.0    2024-06-19  2024-07-06  Adventure
..          ...          ...      ...           ...         ...        ...
430         NaN          NaN    515.0    2025-07-07         NaN        NaN
431         NaN          NaN    526.0    2025-07-05         NaN        NaN
432         NaN          NaN    530.0    2025-07-10         NaN        NaN
433         NaN          NaN    509.0    2025-07-10         NaN        NaN
434         NaN          NaN    523.0    2025-07-08         NaN        NaN

     pages  publication_year    publisher
0    297.0            2015.0  Oasis Books
1    128.0            2017.0   Nile Press
2    160.0            2024.0   Nile Press
3      NaN               NaN          NaN
4    128.0            2017.0   Nile Press
..     ...               ...          ...
430    NaN               NaN          NaN
431    NaN               NaN          NaN
432    NaN               NaN          NaN
433    NaN               NaN          NaN
434    NaN               NaN          NaN

[435 rows x 15 columns]

The 1st 5 rows in the dataset -->
    member_id first_name last_name  grade neighborhood membership_status  \
0       1001      Salma   Ibrahim    8.0        Maadi            Active
1       1002      Fares     Saleh    9.0        Maadi            Active
2       1002      Fares     Saleh    9.0        Maadi            Active
3       1002        NaN       NaN    NaN          NaN               NaN
4       1003     Bassel    Hegazy    6.0        Maadi            Active

    join_date  checkout_id  book_id checkout_date return_date      genre  \
0  2023-04-05       9025.0    525.0    2024-10-24  2024-11-07  Adventure
1         NaN       9013.0    501.0    2024-02-16  2024-02-29  Adventure
2         NaN       9095.0    507.0    2024-06-25  2024-07-07    Science
3         NaN          NaN    521.0    2025-07-08         NaN        NaN
4  2025-04-23       9074.0    501.0    2024-06-19  2024-07-06  Adventure

   pages  publication_year    publisher
0  297.0            2015.0  Oasis Books
1  128.0            2017.0   Nile Press
2  160.0            2024.0   Nile Press
3    NaN               NaN          NaN
4  128.0            2017.0   Nile Press

The last 5 rows in the dataset -->
      member_id first_name last_name  grade neighborhood membership_status  \
430       1104        NaN       NaN    NaN          NaN               NaN
431       1104        NaN       NaN    NaN          NaN               NaN
432       1150        NaN       NaN    NaN          NaN               NaN
433       1201        NaN       NaN    NaN          NaN               NaN
434       1201        NaN       NaN    NaN          NaN               NaN

    join_date  checkout_id  book_id checkout_date return_date genre  pages  \
430       NaN          NaN    515.0    2025-07-07         NaN   NaN    NaN
431       NaN          NaN    526.0    2025-07-05         NaN   NaN    NaN
432       NaN          NaN    530.0    2025-07-10         NaN   NaN    NaN
433       NaN          NaN    509.0    2025-07-10         NaN   NaN    NaN
434       NaN          NaN    523.0    2025-07-08         NaN   NaN    NaN

     publication_year publisher
430               NaN       NaN
431               NaN       NaN
432               NaN       NaN
433               NaN       NaN
434               NaN       NaN

The dataset shape --> (435, 15)

The dataset size --> 6525

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   member_id          435 non-null    int64
 1   first_name         409 non-null    object
 2   last_name          409 non-null    object
 3   grade              371 non-null    float64
 4   neighborhood       409 non-null    object
 5   membership_status  409 non-null    object
 6   join_date          403 non-null    object
 7   checkout_id        391 non-null    float64
 8   book_id            417 non-null    float64
 9   checkout_date      417 non-null    object
 10  return_date        326 non-null    object
 11  genre              391 non-null    object
 12  pages              391 non-null    float64
 13  publication_year   357 non-null    float64
 14  publisher          391 non-null    object
dtypes: float64(5), int64(1), object(9)
memory usage: 51.1+ KB
The dataset info -->
 None

The statistical description of the dataset -->
          member_id       grade  checkout_id     book_id       pages  \
count   435.000000  371.000000   391.000000  417.000000  391.000000
mean   1041.117241    7.560647  9192.611253  513.443645  201.969309
std      26.126819    1.152419   110.279771    8.976053   73.974175
min    1001.000000    6.000000  9001.000000  501.000000  104.000000
25%    1020.000000    7.000000  9097.500000  507.000000  134.000000
50%    1038.000000    8.000000  9193.000000  513.000000  160.000000
75%    1061.000000    9.000000  9287.500000  519.000000  294.000000
max    1201.000000    9.000000  9383.000000  532.000000  338.000000

       publication_year
count        357.000000
mean        2017.560224
std            4.523334
min         2009.000000
25%         2014.000000
50%         2017.000000
75%         2021.000000
max         2024.000000

The columns inside the dataset -->
 ['member_id', 'first_name', 'last_name', 'grade', 'neighborhood', 'membership_status', 'join_date', 'checkout_id', 'book_id', 'checkout_date', 'return_date', 'genre', 'pages', 'publication_year', 'publisher']

The number of duplicated rows --> 8

The duplicated rows -->
      member_id first_name last_name  grade neighborhood membership_status  \
101       1019    Mostafa     Wahba    6.0        Maadi          Inactive
128       1024    Youssef    Hegazy    8.0    Nasr City          inactive
202       1034        Aya     Wahba    9.0    Nasr City            Active
210       1034        Aya     Wahba    9.0    Nasr City            Active
247       1044     Sherif     Saleh    7.0   Heliopolis            active
291       1054      Retaj     Fahmy    6.0   Heliopolis          Inactive
343       1065       Adam     Fahmy    6.0      Zamalek            Active
348       1065       Adam     Fahmy    6.0      Zamalek            Active

      join_date  checkout_id  book_id checkout_date return_date       genre  \
101  2024-07-20       9052.0    501.0    2024-06-20  2024-06-29   Adventure
128  2024-01-04       9194.0    513.0    2024-09-17  2024-10-09     Science
202  2025-01-22       9193.0    519.0    2024-09-15  2024-10-01  Friendship
210  2025-01-22       9180.0    529.0    2024-07-27  2024-08-02     Mystery
247  2024-02-19       9246.0    529.0    2025-06-25  2025-07-04     Mystery
291  2024-03-21       9280.0    517.0    2024-09-06  2024-09-15     Mystery
343  2025-07-12       9296.0    501.0    2024-12-15  2025-01-11   Adventure
348  2025-07-12       9334.0    507.0    2025-12-20  2026-01-05     Science

     pages  publication_year            publisher
101  128.0            2017.0           Nile Press
128  294.0            2021.0          Oasis Books
202  157.0            2014.0           Nile Press
210  298.0               NaN  Cairo Young Readers
247  298.0               NaN  Cairo Young Readers
291  338.0            2015.0          Delta House
343  128.0            2017.0           Nile Press
348  160.0            2024.0           Nile Press
The number of missing values in the dataset for each column -->
 member_id              0
first_name            26
last_name             26
grade                 64
neighborhood          26
membership_status     26
join_date             32
checkout_id           44
book_id               18
checkout_date         18
return_date          109
genre                 44
pages                 44
publication_year      78
publisher             44
dtype: int64

The types of the columns in the dataset -->
 member_id              int64
first_name            object
last_name             object
grade                float64
neighborhood          object
membership_status     object
join_date             object
checkout_id          float64
book_id              float64
checkout_date         object
return_date           object
genre                 object
pages                float64
publication_year     float64
publisher             object
dtype: object